#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
# Update the package list
sudo apt update

# Install Nginx if it's not already installed
sudo apt install -y nginx

# Get the hostname of the server
server_hostname=$(hostname)

# Add the custom header configuration directly to nginx.conf
sudo sed -i "/http {/a \ \ \ \ add_header X-Served-By \"$server_hostname\";" /etc/nginx/nginx.conf

# Test the Nginx configuration for syntax errors
sudo nginx -t

# If the configuration test is successful, reload Nginx to apply changes
if [ $? -eq 0 ]; then
    sudo systemctl reload nginx
fi
