#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
# Update the package list
sudo apt update

# Install Nginx if it's not already installed
sudo apt install -y nginx

# Get the hostname of the server
server_hostname=$(hostname)

# Create a custom Nginx configuration file for the custom header
cat <<EOF | sudo tee /etc/nginx/conf.d/custom_response_header.conf
server {
    listen 80;
    server_name _;

    location / {
        add_header X-Served-By "$server_hostname";
        # Your other Nginx configuration directives go here
    }
}
EOF

# Test the Nginx configuration for syntax errors
sudo nginx -t

# If the configuration test is successful, reload Nginx to apply changes
if [ $? -eq 0 ]; then
    sudo systemctl reload nginx
fi
