#!/usr/bin/env bash
# Installs and setup haproxy

# Update the package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Allow HAProxy management via init script
sudo sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
