#!/usr/bin/env bash
# This is a bash shell script that prints the string "Best School" ten times but If 9, say Hi!.
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done